Lecture 3
Letto228/Angular-learnjs-020223 pull request #18
Opened 2023-02-15 20:55 UTC by Seregb

2023-02-15 20:59 UTC, Seregb commented
Если честно, я немного увлекся и позабыл о том. что нужно вставить stopPropagation 😅. А с текущей структурой и вовсе потерялся в том, куда мне нужно вставить. Буду рад, если подскажешь, где именно нужно остановить всплытие, если оно тут нужно/уместно.

2023-02-16 14:22 UTC, Letto228 commented
Привет!
Мощно, конечно) С утра не осилил, после лекции обязательно просмотрю

2023-02-17 07:06 UTC, Letto228 requested changes
Просмотрел, есть общие комментарии по архитектуре. Давай спишемся в дискорде, наметим время для консультации и на ней разберем нюансы

2023-02-17 07:06 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	productRequest: IProduct = productMock;
По условию, компонент должен получать данные из вне, через инпут

2023-02-17 07:06 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +		if (event) this.countBuyedProduct += 1;
Всегда рекомендую дописывать if блоки полностью, так код станет консистентным и более чистым, в нем будет проще ориентироваться

2023-02-17 07:22 UTC, Seregb commented
Давай. Сегодня я весь день на работе. Будет возможность на выходных уделить время?

2023-02-17 07:40 UTC, Letto228 commented
Написал тебе в дискорде, давай там тогда по времени сориентируемся

2023-02-18 14:46 UTC, Letto228 reviewed
Оставил комментарии с `Договорились: ` в которых зафиксировал договорённости по встрече

2023-02-18 14:46 UTC, Letto228 commented on src/app/core/dialog/dialog.component.ts
> +@Component({
Договорились: выделяем в отдельную директорию и располагаем внутри фичи `card`

2023-02-18 14:46 UTC, Letto228 commented on src/app/core/pagination/pagination.component.ts
> +@Component({
Договорились: что данный компонент не нужен и `mat-paginator` можно использовать напрямую

2023-02-18 14:46 UTC, Letto228 commented on src/app/core/dialog/dialog.component.ts
> +export class DialogComponent {
Договорились: что данный компонент не нужен и будем реализовывать кнопку и использовать сервис `MatDialog` напрямую в `card`

2023-02-18 14:46 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +		if (event) this.countBuyedProduct += 1;
Договорились: всегда писать `{...}`

2023-02-18 14:46 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	countBuyedProduct = 0;
Договорились: выносим счетчик наверх, т.к. это не зона ответсвенности компонента, компонент только отправляет событие

2023-02-19 08:40 UTC, Letto228 requested changes
Отлично!
Пару свежих комментариев дал, посмотри, пожалуйста

2023-02-19 08:40 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +	constructor(public dialog: MatDialog) {}
Не стоит делать сервисы публичными, давай переделаем в `private`

2023-02-19 08:40 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +		this.pictureLength = this.product?.images?.length;
А что, если продукт в инпуте изменится? Тогда кол-во изображений не обновиться. Давай перейдем в сторону `OnChanges` хука.
А вообще, можно прямо в шаблоне прописать данное выражение, оно не сложное.

2023-02-19 08:40 UTC, Letto228 commented on src/app/pages/products-list/card/card.component.ts
> +		this.countBuyedItems.emit(1);
Давай чуть пересмотрим инпут. У тебя же он говорит о покупке, так давай говорить, что произошла покупка такого то продукта: `buyProduct.emit(this.product._id)`. Так родительский компонент сможет положить нужный продукт в корзину, а в качестве sideEffect - увеличить счетчик

2023-02-19 08:40 UTC, Letto228 commented on src/app/pages/products-list/card/dialog-content/dialog-content.component.ts
> +	constructor(public dialogRef: MatDialogRef<DialogContentComponent>) {}
`private`

2023-02-20 06:15 UTC, Letto228 approved these changes
Гуд - апрув
Оставил один комментарий, на будещее, по конструкции, которую ты использовал вместо `if`

2023-02-20 06:15 UTC, Letto228 commented on src/app/core/sidenav/sidenav.component.ts
> +		!this.productsInBasket.includes(event) && this.productsInBasket.push(event);
Не интуитивная конструкция, лучше для такого случая использовать обычный `if`, так легче будет понять, что происходит

2023-02-20 06:15 UTC, closed without merging