feat: create product card
Letto228/Angular-learnjs-020223 pull request #21
Opened 2023-02-16 08:43 UTC by flight-barrel

2023-02-18 14:54 UTC, Letto228 requested changes
Привет!
Все супер, лаконично и со вкусом. Оставил один комментарий по использованию интерполяции, посмотри, пожалуйста

2023-02-18 14:54 UTC, Letto228 commented on src/app/app.component.ts
> +		this._snackBar.open(`Вы добавили '${product.name}' в корзину`, 'Отлично', { duration: 5 * 1000 });
Мне нравится 👍 !

2023-02-18 14:54 UTC, Letto228 commented on src/app/pages/products-list/product-card/product-card.component.html
> +		alt="{{ productInfo.name }}"
Почему тут решил использовать интерполяцию?

2023-02-20 17:34 UTC, flight-barrel commented on src/app/pages/products-list/product-card/product-card.component.html
> +		alt="{{ productInfo.name }}"
Често – не могу ответить :)
Видимо, захотел использовать и байдинг и интерполяцию. Попробовать в общем)

2023-02-21 05:15 UTC, Letto228 commented on src/app/pages/products-list/product-card/product-card.component.html
> +		alt="{{ productInfo.name }}"
Принял)
В реальных проектах лучше использовать binding в таких случаях (когда нужно привязать значение к свойству элемента)

2023-02-21 05:16 UTC, Letto228 approved these changes

2023-02-21 05:16 UTC, closed without merging