feat: initiation custom popup component
Letto228/Angular-learnjs-020223 pull request #31
Opened 2023-02-24 12:45 UTC by Seregb

2023-02-27 15:41 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста

2023-02-27 15:41 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.ts
> +	template: '<div #popup></div>',
Говорили о том, что это не супер практика, давай отдельный файл под `.html` выделим

2023-02-27 15:41 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.ts
> +			this.popupContainer?.clear();
Контейнер стоит очищать в любом случаи. Представь, а что если в template инпут придет новый темлейт, на замен старому? В таком случае в попап будет уже 2 view: один старый и один новый, а по нашей архитектуре, оно должно быть только одно: отображается только то, что находится в template инпуте

2023-02-27 15:41 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.ts
> +	ngOnChanges(): void {
Стоит добавить проверку на изменение нужного инпута. Если появится новый инпут, но и на его изменение будет производиться вставка `TemplateRef`, что согласись, не совсем корректно. По этому хорошей практикой считается выстраивать фильтрацию инпутов в `ngOnChanges ` сразу

2023-02-27 15:43 UTC, Letto228 commented on src/app/app.component.html
> +	<div class="modal-container">
Суть `app-popup-host` в том, чтоыб выполнять позиционирование, а оно у тебя находтся в стилях контента, что не совсем верно. То есть тебе нужно абсолютное позиционирование переместить в логику `app-popup-host`, а `template` отображать внутри `app-popup-host` в обычном потоке (`position: relative`)

2023-02-27 16:26 UTC, Seregb commented
Привет! Увидел, поправлю

2023-03-01 18:39 UTC, Letto228 requested changes
Cool!
Оставил новую, не большую, пачку комментариев, посмотри, пожалуйста

2023-03-01 20:32 UTC, Seregb commented on src/app/shared/popup-host/popup-host.component.ts
> +	popupContainer: ViewContainerRef | undefined;
Да, мое упущение. Поправлю

2023-03-01 21:29 UTC, Letto228 approved these changes
Good! - aprove

2023-03-01 21:29 UTC, closed without merging