feat: add popup component
Letto228/Angular-learnjs-020223 pull request #32
Opened 2023-02-25 10:35 UTC by AnnaPimenova

DZ lecture4

2023-02-27 14:52 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста

2023-02-27 14:52 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.html
> +<div class="popup">
Давай уйдем от данной обертки, кажется в ней нет необходимости, а стили можно на `:host` навесить

2023-02-27 14:52 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.html
> +		<div class="div-container">
А зачем это тут такое наполнение? По идее, данный контент должен через `TemplateRef` создаваться и вставляться

2023-02-27 14:52 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.ts
> +			this.popupContainer?.clear();
Контейнер стоит очищать в любом случаи. Представь, а что если в template инпут придет новый темлейт, на замен старому? В таком случае в попап будет уже 2 view: один старый и один новый, а по нашей архитектуре, оно должно быть только одно: отображается только то, что находится в template инпуте

2023-02-28 15:51 UTC, AnnaPimenova commented
привет. Чуть переделала, поправила. Посмотри, так?

2023-03-01 06:15 UTC, Letto228 commented
Огонь!
Остался 1 комментарий актуальным - https://github.com/Letto228/Angular-learnjs-020223/pull/32#discussion_r1118848480
Давай спишемся по нему в дискорде и там обсудим

2023-03-01 06:45 UTC, AnnaPimenova commented
Поняла, что не так. Поправила))

2023-03-01 18:44 UTC, Letto228 approved these changes
Огонь 🔥!
Оставил комментарий на будущее, он не критичен, по этому закрыл МР. Но прочитать стоит)

2023-03-01 18:44 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.html
> +<div class="div-container">
В целом, можно было бы избавиться от этого контейнера, вместо него, стили можно было бы навесть на `:host` селектор, тем самым мы бы перевесили визуализацию на хост-элемент компонента.
Еще я бы нейминги для классов рекомендовал бы более информативные использовать, в нашем контексте можно было бы написать просто `container` and `wrapper`, или заменить `div` -> `popup`

2023-03-01 18:44 UTC, closed without merging