DZ lecture-5
Letto228/Angular-learnjs-020223 pull request #33
Opened 2023-02-25 15:48 UTC by AnnaPimenova

DZ lecture-5

2023-02-27 14:59 UTC, Letto228 requested changes
Привет!
Супер, решение супер. Оставил пару комментариев по неймингу и консстантному свойству

2023-02-27 14:59 UTC, Letto228 commented on src/app/shared/scroll-loading/scroll-loading.directive.ts
> +	private offset = 100;
Я бы это вынес в константу, чтобы не нагружать класс константными свойствами

2023-02-27 14:59 UTC, Letto228 commented on src/app/shared/scroll-loading/scroll-loading.directive.ts
> +		const scrollDirectionDown = target.scrollTop < this.prevScrolled;
`scrollDirectionDown` -> `isScrollDirectionUp`? Кажется, что тут вычисляется скролл вверх

2023-02-27 14:59 UTC, Letto228 commented on src/app/shared/scroll-loading/scroll-loading.directive.ts
> +	private offset = 100;
Если есть аргументы в сторону свойства, а не константы, то стоит добавить `readonly` говорящий о неизменности данного свойства

2023-02-28 06:29 UTC, AnnaPimenova commented on src/app/shared/scroll-loading/scroll-loading.directive.ts
> +		const scrollDirectionDown = target.scrollTop < this.prevScrolled;
Согласна, поменяла нейминг

2023-02-28 06:31 UTC, AnnaPimenova commented on src/app/shared/scroll-loading/scroll-loading.directive.ts
> +	private offset = 100;
Добавила readonly

2023-02-28 06:39 UTC, Letto228 approved these changes
Супер - апрув

2023-02-28 06:39 UTC, closed without merging