Lecture-5
Letto228/Angular-learnjs-020223 pull request #34
Opened 2023-02-26 17:10 UTC by AVoits

2023-02-27 15:10 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста

2023-02-27 15:10 UTC, Letto228 commented on src/app/shared/scroll-load/scroll-load.directive.ts
> +		const top = Math.round(target.scrollTop);
В чем смысл округления?

2023-02-27 15:10 UTC, Letto228 commented on src/app/shared/scroll-load/scroll-load.directive.ts
> +		const bottomPosition = Math.round(target.scrollTop + target.offsetHeight);
Кажется, что `clientHeight` больше подходит для данных целей, почему решила взять `offsetHeight`?

2023-02-27 16:45 UTC, AVoits commented on src/app/shared/scroll-load/scroll-load.directive.ts
> +		const top = Math.round(target.scrollTop);
При скролле вверх значение бывает дробным

2023-02-27 16:56 UTC, AVoits commented on src/app/shared/scroll-load/scroll-load.directive.ts
> +		const bottomPosition = Math.round(target.scrollTop + target.offsetHeight);
конкретно в данном случае можно взять любой, тут они одинаковы. offsetHeight включает ширину элемента втч рамки (бордюр и сами скроллы), clientHeight  только область самого элемента. Горизонтального скролла нет, так что они по размеру одинаковы.

2023-02-28 06:43 UTC, Letto228 commented on src/app/shared/scroll-load/scroll-load.directive.ts
> +		const bottomPosition = Math.round(target.scrollTop + target.offsetHeight);
А что, если у нас поменяется верстка и добавится бордер? Кажется, в таком случаи `bottomPosition` будет рассчитываться не совсем корректно

2023-03-01 11:39 UTC, AVoits commented on src/app/shared/scroll-load/scroll-load.directive.ts
> +		const bottomPosition = Math.round(target.scrollTop + target.offsetHeight);
Да, действительно. Заменила на clientHeight

2023-03-01 17:54 UTC, Letto228 approved these changes
Огонь! - апрув

2023-03-01 17:54 UTC, closed without merging