feat: add categories navigation
Letto228/Angular-learnjs-020223 pull request #51
Opened 2023-03-12 13:37 UTC by Kojanni

Переключение по подкатегориям

2023-03-12 21:40 UTC, Letto228 requested changes
Привет!
Оставил парочку уточняющих комментариев, буду ждать ответа по ним

2023-03-12 21:40 UTC, Letto228 commented on src/app/core/sidenav/categories-select/categories-select-routing.module.ts
> +export class CategoriesSelectRoutingModule {}
Странноватый модуль к нам тут затесался) Это рудимент или так задумано?

2023-03-12 21:40 UTC, Letto228 commented on src/app/pages/products-list/products-list-routing.module.ts
> +		path: 'categories/:categoryId',
Думаю, в таком случае стоит продумать поведение при переходе на `categories` путь, чтобы улучшить UX

2023-03-12 21:40 UTC, Letto228 commented on src/app/pages/products-list/products-list.component.ts
> +		filter(Boolean),
А на странице без категории продукты продолжают загружаться?

2023-03-14 05:27 UTC, Kojanni commented on src/app/core/sidenav/categories-select/categories-select-routing.module.ts
> +export class CategoriesSelectRoutingModule {}
Это да, я разбиралась как оно там работает)

2023-03-14 05:29 UTC, Kojanni commented on src/app/pages/products-list/products-list.component.ts
> +		filter(Boolean),
Хорошее замечание, глаз-алмаз, действительно возвращает пустоту. Поправила этот момент

2023-03-14 05:29 UTC, Kojanni commented on src/app/pages/products-list/products-list-routing.module.ts
> +		path: 'categories/:categoryId',
Добавила переход к полному списку

2023-03-15 05:09 UTC, Letto228 approved these changes
Огонь! - апрув

2023-03-15 05:09 UTC, closed without merging